M48
; DRILL file {KiCad 7.0.9} date Sun Jun 23 11:57:03 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-06-23T11:57:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X5.828Y-2.94
X6.328Y-2.94
T2
X4.9052Y-5.4364
X4.91Y-2.79
X5.787Y-4.492
X6.353Y-4.978
X7.36Y-2.79
X7.3652Y-5.4364
T0
M30
