M48
; DRILL file {KiCad 7.0.9} date Mon Apr  8 18:15:03 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-08T18:15:03-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1280
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1378
%
G90
G05
T1
X4.4299Y-3.0998
X4.4299Y-3.5998
T2
X4.33Y-2.48
X4.33Y-4.22
X7.97Y-2.48
X7.97Y-4.22
T0
M30
